# Generated by Django 4.2.7 on 2023-11-26 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='наименование')),
                ('slug_name', models.SlugField(max_length=255, unique=True, verbose_name='slug-имя')),
                ('picture', models.ImageField(upload_to='category/', verbose_name='изображение')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'категории',
            },
        ),
        migrations.CreateModel(
            name='Dimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.PositiveIntegerField(verbose_name='высота')),
                ('width', models.PositiveIntegerField(verbose_name='ширина')),
            ],
            options={
                'verbose_name': 'размер изображения',
                'verbose_name_plural': 'размеры изображения',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='наименование')),
                ('slug_name', models.SlugField(max_length=255, unique=True, verbose_name='slug-имя')),
                ('picture', models.ImageField(upload_to='subcategory/', verbose_name='изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.category', verbose_name='категория')),
            ],
            options={
                'verbose_name': 'подкатегория',
                'verbose_name_plural': 'подкатегории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='наименование')),
                ('slug_name', models.SlugField(max_length=255, unique=True, verbose_name='slug-имя')),
                ('picture', models.ImageField(height_field='dimensions.height', upload_to='product/', verbose_name='изображение', width_field='dimensions.width')),
                ('price', models.PositiveIntegerField(verbose_name='цена')),
                ('dimensions', models.ManyToManyField(to='shop.dimension', verbose_name='размер изображения')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory', verbose_name='подкатегория')),
            ],
            options={
                'verbose_name': 'продукт',
                'verbose_name_plural': 'продукты',
            },
        ),
    ]
