# Generated by Django 4.2.7 on 2023-11-26 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='dimensions',
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(height_field='dimensions.height', upload_to='product/', verbose_name='изображение', width_field='dimensions.width')),
                ('dimensions', models.ManyToManyField(to='shop.dimension', verbose_name='размер изображения')),
            ],
            options={
                'verbose_name': 'изображение',
                'verbose_name_plural': 'изображения',
            },
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='shop.picture', verbose_name='изображение'),
        ),
    ]
